### ISSUE TITLE
https: is not a valid URL.

### ISSUE THREAD

**Issue by fontiela** [iris-edu/gmv#1]
When I run GMV using AM network (RaspberryShake) I get the following error:
``` from RASPISHAKE_0 (https:/) failed: The FDSN service base URL `https:` is not a valid URL.```

likely the error cause is in the file located at [http://service.iris.edu/irisws/fedcatalog/1/datacenters]( http://service.iris.edu/irisws/fedcatalog/1/datacenters ) where raspberryshake URL is a secure one instead of a regular http: .

**Comment by manoch-iris** [comment]
Hi @fontiela, Would you please send me the run command you are using and also run the GMV code in the verbose mode (-v) and forward me the output of the code? Thanks!
